### ISSUE TITLE
Error when attempting to push results to database

### ISSUE THREAD

**Issue by hutchinsonmiri** [DOH-JDJ0303/bigbacter-nf#16]
### Description of the bug

Hi there, I ran big-bacter for the first time and the main process seems to have completed without error, but when I attempt to push the results to the database, I get the following error message, below. And then, upon attempting to re-run the code, I get a second error during poppunk assignment (also below), which seems to indicate an issue with writing a directory. I checked the database and it looks like all of the isolates have populated under the snippy directory, but not in the assembly directory. Thank you in advance!!

### Command used and terminal output

```console
$ nextflow run DOH-JDJ0303/bigbacter-nf -r main -profile docker --input samplesheet.csv --outdir results --db /home/SequencingAdmin/nmdoh_data_storage/big-bacter-db/ --push true -resume
ERROR 1:
ERROR ~ No such file or directory: /home/SequencingAdmin/nmdoh_data_storage/big-bacter-db/Acinetobacter_baumannii/clusters/00001/snippy/2024030700_T1.tar.gz

 -- Check script '/home/mhutchinson/.nextflow/assets/DOH-JDJ0303/bigbacter-nf/./workflows/bigbacter.nf' at line: 142 or see '.nextflow.log' file for more details

ERROR 2:
Assigning clusters with PopPUNK.

Matplotlib created a temporary cache directory at /tmp/matplotlib-cerexqj0 because the default path (/home/mambauser/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Fontconfig error: No writable cache directories
PopPUNK: assign
	(with backend: sketchlib v2.1.4
	 sketchlib: /opt/conda/envs/poppunk-env/lib/python3.10/site-packages/pp_sketchlib.cpython-310-x86_64-linux-gnu.so)
Mode: Assigning clusters of query sequences


Graph-tools OpenMP parallelisation enabled: with 8 threads
--output and --db must be different to prevent overwrite.
```

### Relevant files

[nextflow.log](https://github.com/user-attachments/files/18099485/nextflow.log)

### System information

Nextflow version: 23.04.2
Hardware: Cloud
Executor: Azure VM
Container engine: (e.g. Docker, Singularity, Conda, Podman, Shifter, Charliecloud, or Apptainer)
OS: Ubuntu Linux
Version of nf-core/bigbacter: 1.0.0

**Comment by DOH-JDJ0303** [comment]
Hi @hutchinsonmiri. Sorry to hear you are running into issues. It is not immediately clear to me the source of these issues, so some additional info would be helpful! 

1. Can you share the `.nextflow.log` file from the first run you performed? It should be named `.nextflow.log.2` if you have only run the pipeline 3 times.
2. Can you confirm the file at path `/home/SequencingAdmin/nmdoh_data_storage/big-bacter-db/Acinetobacter_baumannii/clusters/00001/snippy/2024030700_T1.tar.gz` exists, has the correct permissions, and is not somehow a symlink.
3. Can you confirm there is more than one PopPUNK database file in `/home/SequencingAdmin/nmdoh_data_storage/big-bacter-db/Acinetobacter_baumannii/pp_db/`. This directory should contain `0000000000.tar.gz` and one other file if things were pushed properly.

If this is your first time running BigBacter, then it may be worth deleting the database and starting over. If you run into the same issue again, you could try running the pipeline with `--db_info false`, as it appears the first error occurred while trying to gather information about your bigbacter database.

Regarding the second error - I am not sure what is going on, but my hunch is that if we can solve the first issue it will go away.

**Comment by hutchinsonmiri** [comment]
Hi there, thanks for your response!
So the nextflow log above is actually the` .nextflow.log.2 ` but I removed the .2 suffix because github was throwing an error when I tried to upload it. Sorry for the confusion!

And yes, I see the path ` /home/SequencingAdmin/nmdoh_data_storage/big-bacter-db/Acinetobacter_baumannii/clusters/00001/snippy/2024030700_T1.tar.gz` and it does not appear to be a symlink and I have full permissions. Interestingly, there is no corresponding file here: `/home/SequencingAdmin/nmdoh_data_storage/big-bacter-db/Acinetobacter_baumannii/clusters/00001/assembly/` but other samples have populated here.

Also, I can confirm that there are two database files: `0000000000.tar.gz` and one from the day I first ran the pipeline: `1733873179.tar.gz` . 

I've tried deleting and reinstalling the Acinetobacter database but encountered the same error. I will say, I am trying to push ~30 samples to the db, so could that be an issue?

Thanks a bunch!!

**Comment by DOH-JDJ0303** [comment]
Thank you for the additional info. Would you happen to have the `.nextflow.log` file for the first run (the one where you have `--push false`)? I want to make sure nothing funky is going on during this initial process. 

Also, did you get a chance to run with `--db_info false`? It appears the error is caused by the `db_info` function looking for a file that "doesn't exist". This is odd because the function will only check files that it has detected are present.

In the meantime, I think I have a solution that will help move things forward. I will let you know when it is ready. I appreciate your patience!

**Comment by hutchinsonmiri** [comment]
[nextflow (2).log](https://github.com/user-attachments/files/18115587/nextflow.2.log)
Thanks! Here is the first log file.
And when you suggest to run with `--db_info false`, would that be while pushing to the db, ie `--push true`? Appreciate the help!

**Comment by DOH-JDJ0303** [comment]
Yep, I suspect that running `--db_info false` with `--push true` may resolve the issue for now. I will hopefully have a long-term solution shortly if that is truly the issue.

**Comment by hutchinsonmiri** [comment]
That did the trick! All of the samples have been pushed to both the `snippy` and `assembly` directories.

**Comment by hutchinsonmiri** [comment]
Likewise, thanks!!
