### ISSUE TITLE
--db path must be created prior to running -entry PREPARE_DB

### ISSUE THREAD

**Issue by slsevilla** [DOH-JDJ0303/bigbacter-nf#5]
### Description of the bug

The path provided to the argument `--db` has to be created prior to running. For example:
```
nextflow run /bigbacter-nf/main.nf \
   -profile docker \
   -entry PREPARE_DB \
   --input /config/pp_db_list.csv \
   --db /bigbacter/db
```
The directory `/bigbacter/db` has to exist prior to run. If it doesn't a non-helpful error is printed: 

```
Unable to read script: '/bigbacter-nf/./workflows/prepare_db.nf' -- cause: /bigbacter/db
```

I think updating the Wiki so this is clear is enough to address this, but I can also edit my fork to check and create this dir if it doesn't exist - not sure which you'd prefer.

**Comment by DOH-JDJ0303** [comment]
Thanks, Sam! This should be fixed now. Feel free to submit pull requests if you want to collaborate!
