### ISSUE TITLE
Gubbins issue - RuntimeError: cannot cache function 'seq_to_int': no locator available for file

### ISSUE THREAD

**Issue by DOH-JDJ0303** [DOH-JDJ0303/bigbacter-nf#7]
### Description of the bug

Creating separate issue for problem described in [issue 4](https://github.com/DOH-JDJ0303/bigbacter-nf/issues/4). Will update Gubbins containers once problems with Python/Numba are resolved by Bioconda/Gubbins developers.

References:
[Gubbins Issue 396](https://github.com/nickjcroucher/gubbins/issues/396)
[Bioconda pull 46713](https://github.com/bioconda/bioconda-recipes/pull/46713)

**Comment by rpetit3** [comment]
Hi @DOH-JDJ0303 

On the Nextflow side, I think this might be semi-related to Nextflow no longer mounting home directories by default with Singularity. Here's a related issue over on Bactopia https://github.com/bactopia/bactopia/issues/500

From nextflow docs:

_Changed in version 23.07.0-edge: Nextflow no longer mounts the home directory when launching a Singularity container. To re-enable the old behavior, set the environment variable NXF_SINGULARITY_HOME_MOUNT to true._

Exporting `NXF_SINGULARITY_HOME_MOUNT` will make things play nicely.

```
export NXF_SINGULARITY_HOME_MOUNT=true
```

On the Bactopia side, I'm going to play around with some more elegant approaches then asking users to add a variable to their ENV.

Cheers,
Robert

**Comment by DOH-JDJ0303** [comment]
Hi @rpetit3, this looks like the fix! I will share any elegant methods if they come my way. Thanks!

**Comment by hkaspersen** [comment]
Hello!
I tried your suggested solution with `export NXF_SINGULARITY_HOME_MOUNT=true`, but this did not work for me. I am using nextflow version 23.10.1. Any suggestions?

**Comment by DOH-JDJ0303** [comment]
Hi @hkaspersen. Sorry to hear this is still an issue. Can you provide more info about your compute environment? Is your error also caused by `Numba`? Are you able to test a different containerization platform like `docker` or `podman`?

**Comment by hkaspersen** [comment]
Hello again, sorry this was an error from my side. I completely forgot that I had switched over to Apptainer from Singularity, so I simply had to change it from `export NXF_SINGULARITY_HOME_MOUNT=true` to `export NXF_APPTAINER_HOME_MOUNT=true`, which worked perfectly. Thanks!
